//
//  PictureUsUserSetting1.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.6
//

import Foundation
import UIKit
import AWSDynamoDB

class PictureUsUserSetting1: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _circle: String?
    var _doubleTap: String?
    var _down: String?
    var _downLeft: String?
    var _downRight: String?
    var _iMessageContacts: String?
    var _iMessageText: String?
    var _left: String?
    var _right: String?
    var _tap: String?
    var _up: String?
    var _upLeft: String?
    var _upRight: String?
    
    class func dynamoDBTableName() -> String {

        return "pictureusaws-mobilehub-915003100-PictureUsUserSetting1"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func JSONKeyPathsByPropertyKey() -> [NSObject : AnyObject] {
        return [
               "_userId" : "userId",
               "_circle" : "Circle",
               "_doubleTap" : "DoubleTap",
               "_down" : "Down",
               "_downLeft" : "DownLeft",
               "_downRight" : "DownRight",
               "_iMessageContacts" : "IMessageContacts",
               "_iMessageText" : "IMessageText",
               "_left" : "Left",
               "_right" : "Right",
               "_tap" : "Tap",
               "_up" : "Up",
               "_upLeft" : "UpLeft",
               "_upRight" : "UpRight",
        ]
    }
}
